# Generated by Django 5.2.12 on 2026-04-27 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=6)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=6)),
                ("user_id", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
