networks:
  dev:
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - static_volume:/user/staticfiles
    command: >
          sh -c "python manage.py collectstatic --noinput &&
                 chmod -R 755 /user/staticfiles &&
                 python manage.py migrate &&
                 gunicorn siteweather.wsgi:application --bind 0.0.0.0:8000"
    networks:
      - dev

  redis:
    image: redis:7.2-alpine 
    container_name: redis_cache
    expose:
      - 6379
    networks:
      - dev

  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - dev

  nginx:
    build:
      context: ./docker/nginx/
    volumes:
      - static_volume:/user/staticfiles
    depends_on:
      - django
    ports:
      - "8001:80"
    networks:
      - dev

volumes:
  static_volume:
  postgres_data: